api-version: 1.13
name: ChestLink
main: link.ChestLink
version : 1.0
commands:
   ChestLink:
      description: blank
      usage: /<command>
   Fixdata:
      description: blank
      usage: /<command>   
permissions:
    ChestLink.Make:
      default: op
    ChestLink.fixdata:
      default: op 